# Standalone docker-compose file for testing

services:
  tds:
    build: .
    container_name: tds
    depends_on:
      - tds-db
    environment:
      - DB_HOST=tds-db
      - DB_PORT=5432
      - DB_USER=tds_user
      - DB_NAME=tds_db
      - DB_PASSWORD=tds_password
      - CORS_ORIGINS="*"
      - BENTO_AUTHZ_SERVICE_URL=""
    volumes:
      - $PWD/lib:/tds/lib
    ports:
      - "5000:5000"

  tds-db:
    image: postgres:16
    container_name: tds-db
    environment:
      - POSTGRES_USER=tds_user
      - POSTGRES_PASSWORD=tds_password
      - POSTGRES_DB=tds_db
    expose:
      - 5432
