# Standalone docker-compose file for local dev

services:
  tds:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    container_name: tds
    depends_on:
      - tds-db
    environment:
      - BENTO_UID=${UID}
      - DB_HOST=tds-db
      - DB_PORT=5432
      - DB_PASSWORD_FILE=/run/secrets/tds_db_password
      - CORS_ORIGINS="*"
      - BENTO_AUTHZ_SERVICE_URL=""
    secrets:
      - tds_db_password
    volumes:
      - $PWD:/tds     # mounts local repository
    ports:
      - "5000:5000"

  tds-db:
    image: postgres:16
    container_name: tds-db
    environment:
      - POSTGRES_USER=tds_user
      - POSTGRES_DB=tds_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/tds_db_password
    secrets:
      - tds_db_password
    expose:
      - 5432

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

secrets:
  tds_db_password:
    file: dev_db_password.txt
