# Standalone docker-compose file for testing

services:
  tds:
    build: .
    container_name: tds
    depends_on:
      - tds-db
    environment:
      - DATABASE_URI=postgres://tds_user:tds_password@tds-db:5432/tds_db
      - CORS_ORIGINS="*"
      - BENTO_AUTHZ_SERVICE_URL=""
    ports:
      - "5000:5000"

  tds-db:
    image: postgres:16
    container_name: tds-db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tds_user
      - POSTGRES_PASSWORD=tds_password
      - POSTGRES_DB=tds_db
    expose:
      - 5432

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
