# Standalone docker-compose file to run local tests using the PG database

services:
  tds:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
      labels:
        - takuan.image.kind=test
    container_name: tds
    depends_on:
      - tds-db
    environment:
      - TDS_USER_NAME=tds
      - TDS_UID=${UID}
      - DB_HOST=tds-db
      - DB_PORT=5432
      - DB_USER=tds_user
      - DB_NAME=tds_db
      - DB_PASSWORD=tds_password
      - CORS_ORIGINS="*"
      - AUTHZ_ENABLED=True
    volumes:
      # Mounts local repository
      - $PWD:/tds
      # Use API key plugin for authz testing
      - $PWD/authz_plugins/api_key:/tds/lib
      - $PWD/authz_plugins/api_key/example.env:/tds/lib/.env # map example.env to .env
    labels:
      - takuan.container.kind=test

  tds-db:
    image: postgres:18
    container_name: tds-db
    environment:
      - POSTGRES_USER=tds_user
      - POSTGRES_PASSWORD=tds_password
      - POSTGRES_DB=tds_db
    expose:
      - 5432
