name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12", "3.13" ]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        name: Set up Python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Format check
        run: |
          poetry run ruff format --check
      - name: Lint check
        run: |
          poetry run ruff check
